# Generated by Django 4.0.4 on 2022-05-27 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'carrera',
                'verbose_name_plural': 'carreras',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'localidad',
                'verbose_name_plural': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='apellido')),
                ('addres', models.CharField(max_length=100, null=True, verbose_name='domicilio')),
                ('number_phone', models.CharField(max_length=25, null=True, verbose_name='numero de telefono')),
                ('id_location_connect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Teacher_id_location_connect', to='Gestion.location', verbose_name='localidad')),
            ],
            options={
                'verbose_name': 'profesor',
                'verbose_name_plural': 'profesores',
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='nombre')),
                ('id_career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Matter_id_career', to='Gestion.career', verbose_name='carrera')),
                ('id_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Matter_id_teacher', to='Gestion.teacher', verbose_name='profesor')),
            ],
            options={
                'verbose_name': 'materia',
                'verbose_name_plural': 'materias',
            },
        ),
    ]
